server.port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgresdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 1800000
      minimumIdle: 5
      maximumPoolSize: 20
      poolName: SpringBootJPAHikariCP
  #      schema: users

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto: none
  # This line is only needed if you are using flyway for database migrations
# and not using the default location of `db/migration`
spring.flyway.locations=classpath: db/migration/